####组织树表的初始数据
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('0','组织机构树','-1','1');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1','浪潮集团','0','1');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('101','总部','1','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('102','浪潮信息','1','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('103','浪潮软件','1','1');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1031','人力资源部','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1032','财务部','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1033','技术研究中心','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1034','质保中心','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1035','运营中心','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1036','电子商务事业本部','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1037','电子政务','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1038','系统服务事业部','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('1039','特殊行业事业部','103','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('104','浪潮国际','1','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('105','浪潮超越 ','1','0');
INSERT INTO DEMO_ORGAN (ID,NAME,PARENT_ID,IS_PARENT) VALUES('106','浪潮华光','1','0');

####用户表初始化数据
INSERT INTO DEMO_USER (USER_ID,USER_NAME,NICKNAME,PASSWORD,ACT_STATUS) VALUES("1","dddddddd","dddddddddddddddddddddddddd","123","N");
INSERT INTO DEMO_USER (USER_ID,USER_NAME,NICKNAME,PASSWORD,ACT_STATUS) VALUES("2","dddddddd","ddddddddddddddddddddddddddd","123","N");
INSERT INTO DEMO_USER (USER_ID,USER_NAME,NICKNAME,PASSWORD,ACT_STATUS) VALUES("3","dddddddd","ddddddddddddddddddddddddddd","123","N");

####用户档案表初始化数据
INSERT INTO DEMO_ARCHIVES (USER_ID,GENDER,BIRTHDAY,EDUCATION,ID,SCHOOL,EMAIL) VALUES("1","M","2014-01-15","1","1234567789","山东大学","pwj@qq.com");

####产品表初始化数据
INSERT INTO DEMO_PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MANU, PRODUCT_NUM, PRODUCT_DATE, PRODUCT_PRICE)VALUES("1","123456","苹果","0","MANU",2,"2016-1-25",2.3);
INSERT INTO DEMO_PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MANU, PRODUCT_NUM, PRODUCT_DATE, PRODUCT_PRICE)VALUES("2","135790","菠菜","1","MANU",2,"2016-1-25",5.6);
INSERT INTO DEMO_PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MANU, PRODUCT_NUM, PRODUCT_DATE, PRODUCT_PRICE)VALUES("3","234567","猪肉","1","MANU",2,"2016-1-25",12.4);