##组件表外键
ALTER TABLE UE_COM ADD CONSTRAINT UE_COM_FK1 FOREIGN KEY(TYPE_ID) REFERENCES UE_COM_TYPE(ID);

##用户档案外键
ALTER TABLE DEMO_ARCHIVES ADD CONSTRAINT DEMO_ARCHIVES_FK1 FOREIGN KEY (USER_ID) REFERENCES DEMO_USER (USER_ID);